tcpdump.c

capng_clear needs to be called before capng_change_id can be called within
droproot.  Otherwise, an (unusable) error message is output: "error : ret -1" and it fails to drop root privileges.
This also fixes the dropping of the CAP_SETGID capability.  Previously,
CAP_SETUID was being dropped twice.

Make sure to init capng before dropping root.

---

tcpdump.c

- Only set the SETUID/SETGID capabilities if required (i.e. we'll be changing
the effective UID).
- Only set the CAP_DAC_OVERRIDE capability if writing out to a file (i.e. the -w
flag was provided).
- Fix the calls to capng_clear to pass CAPNG_SELECT_BOTH so that the traditional
and bounding capabilities are set.
- Only remove CAP_DAC_OVERRIDE from the permitted set after opening the write
file if neither -G nor -C flag was provided.  We always drop it from the
effective set immediately after opening the write file.  During file rotation,
we reacquire it immediately before and drop it immediately after opening the
file.

Fix issues with the setting of libcap-ng capabilities.

---

CONTRIBUTING

Hey everyone,
Just had this lying around when I was reading the CONTRIBUTING file way back. Nothing special, just a few typo/grammar fixes.
Thanks!
-- Andrew

Just fixes a few typos and grammatical issues

---

tcpdump.c

Update helper text to be more descriptive about the "-z command" option. 
Just like http://www.tcpdump.org/tcpdump_man.html

Change -z command help text to -z postrotate-command

---

CREDITS

The previous email is no longer valid.

Fix my email address

---

CONTRIBUTING
update-test.sh

Improve "6) Add/update sample.pcap files" in CONTRIBUTING, provide and suggest using update-test.sh in CONTRIBUTING.

Improve CONTRIBUTING (sample.pcap)

---

aclocal.m4

I noticed that the "additional-libs" block in `AC_LBL_LIBPCAP` in never reached.
This "fix" should therefore help in adding any additional libs pcap depends on/was linked with to, `LIBS` (including ws2_32 on windows).
Heads up: I'm not sure if I indented correctly. I don't have syntax highlighting for m4. Sorry in advance.
I also only tried it on windows so let's see what travis has to say to this.

Some tweaks for AC_LBL_LIBPCAP

---

print-gre.c

I'm the original author. Feel free to pull this and nuke clause 3/4.

remove clauses 3/4 from license

---

print-bgp.c

The implementations of MP_REACH_NLRI and MP_UNREACH_NLRI attributes had duplicate implementations for each supported AFI/SAFI, and were out of sync (SAFNUM_RT_ROUTING_INFO had no handling for UNREACH).
The fact of having two implementations for each AFI/SAFI makes it easy to forget one when working on the other, as evidenced by my discovery of a locally-implemented printer that had only MP_REACH but not MP_UNREACH code.  Having a common implementation will eliminate this problem for people adding new AFI/SAFI support (and, of course, when fixing bugs in the existing implementation)
Coverage of the new code against existing tests is https://github.com/fenner/tcpdump/wiki/bgp_print_nlri-code-coverage-with-existing-tests .

Factor BGP NLRI printing into a reusable function

---

.appveyor.yml

AppVeyor: Update Npcap SDK to 1.07

---

aclocal.m4
configure

This is needed for building on Haiku.

autoconf: search for gethostbyaddr() in libnetwork

---

print-tcp.c

TCP: Test ports < 1024 in port order to select the printer

---

tcpdump.1.in

The packet types are not really obvious and I didn't find them to be documented yet.

man: Document interface and packet type

---

print-icmp.c

For a future change, we refactor RFC4884 object printing into its own function.  This change just moves and reindents the lines in question.

ICMP: refactor RFC4884 object printing

---

aclocal.m4
nameser.h

Retire all remaining IRIX and SINIX support.

---

print-pflog.c

Enable ND_LONGJMP_FROM_TCHECK and remove a 'trunc' label.
Add MAX_PFLOG_HDRLEN and use it for a test.
Use ND_ICHECK_U() in length tests and add an 'invalid' label.
Don't check the tructation with ND_TCHECK_SIZE(hdr), because the sizeof(hdr) depend on the OS. Use ND_TCHECK_LEN(hdr, hdrlen).
Increment ndo_ll_hdr_len only in non-truncation case.

pflog: Modernize packet parsing

---

print-bgp.c

Fix error code 7 and add error code 8
https://www.iana.org/assignments/bgp-parameters/bgp-parameters.xhtml#bgp-parameters-3

Align BGP error code printing with IANA registry

---

print-nflog.c

Enable ND_LONGJMP_FROM_TCHECK and remove a 'trunc' label.
Use ND_ICHECK_U()/ND_ICHECK_ZU in length tests and add an 'invalid' label.

NFLOG: Modernize packet parsing

---

doc/README.Win32.md

doc: fix RADME.Win32.md issues. [skip ci]

---

cmakeconfig.h.in
configure.ac

Autoconf: Do not check for C99 uintptr_t.

---

print-esp.c

This makes the code cleaner anyway and avoids branching.

Prefer calloc over malloc

---

.cirrus.yml
CHANGES
CMakeLists.txt
build.sh
build_common.sh
build_matrix.sh

CI: Synchronize with the master branch.

---

CMakeLists.txt
cmake/Modules/FindCRYPTO.cmake

Do the same sort of stuff that configure does, but CMake-style.

CMake: use pkg-config and Homebrew when looking for libcrypto.

---

aclocal.m4

Now that we have PKG_CHECK_MODULE(), we don't need to roll our own code to use pkg-config to look for libpcap - just use PKG_CHECK_MODULE().
Improve some PKG_ macro comments while we're at it.

autoconf: use PKG_CHECK_MODULE() to check for libpcap.

---

print-msdp.c

Make sure we don't run past either 1) the end of the packet data (using ND_TCHECK_LEN() for fields we don't fetch and print) or 2) the end of the TLV (with a check of length before fetching the T and L, and checks of L before fetching any further data).
Don't advance sp past the T and L, or decrement length for the T and L, before parsing the V, so we don't have to subtract 3 from sp in some cases.
Add some comments.
Define ND_LONGJMP_FROM_TCHECK to do new-style checks.

msdp: do some additional bounds checks.

---

tcpdump.c

They do various error checks; use them instead of strto*() or atoi().

Add routines to parse numeric command-line arguments, and use them.

---

CHANGES
CMakeLists.txt
addrtoname.c
cmakeconfig.h.in
configure.ac
print.c
tcpdump.1.in
tcpdump.c
tests/TESTlib.pm
tests/TESTrun

This includes a follow-up to the-tcpdump-group/libpcap#1454.

Fix "ip broadcast" with -f and other assorted improvements
