print-arp.c

The target's hardware and protocol address were being printed instead of the sender's hardware and protocol address.
This is now handled the same way as a ARP response.
I found this bug several years ago, but there was not an easy way for me to submit a patch.  Once I found out this project was now being hosted on GitHub, I took a look and found the bug still existed, and decided to submit a fix.

Fixed bug in arp_print() in handling of inverse arp responses

---

tcpdump.c

Without these changes pcap_dump_ftell() will return -1 and set errno to
ENOTCAPABLE.
This allows you to do:
tcpdump -C 1 -W 5 -w foo.pcap
Without these changes it will never rotate to foo.pcap1 and continue writing
to foo.pcap0 forever.
Discussed at: http://unix.derkeiler.com/Mailing-Lists/FreeBSD/current/2014-09/msg00142.html

Add CAP_FCNTL and use cap_fcntls_limit().

---

print-tcp.c
tcp.h

https://tools.ietf.org/html/rfc7413
TCP Fast Open has left draft status and now has an IANA designated option number. This patch adds support for that.

Add support for TCP Fast Open official IANA option number

---

tcpdump.c

We have removed all instances of these messages in FreeBSD as they serve
little purpose and break some comsumers.

Remove "capability mode sandbox enabled" message.

---

netdissect.h
print.c
print.h
tcpdump.c

This set of changes further improves the split between the frontend and backend by eliminating a shared global netdissect_object and removing several members from the struct that deal with frontend packet processing details.

Remove global netdissect_object and remove non-dissection related fields

---

print-domain.c

"DO" is a better description of the DNSSEC OK bit in the EDNS0 OPT record.  See RFC 3225 section 3.  There may be other bits allocated in the future that call themselves "Something OK".

For DNS messages, represent the "DNSSEC OK" bit as "DO" instead of "OK"

---

print-dccp.c

Fix warning:
```
print-dccp.c(500): warning C4456: declaration of 'cp' hides previous local declaration
print-dccp.c(277): note: see declaration of 'cp'
```

Fix print-dccp.c warning

---

print-icmp.c

Fix warnings in print-dccp.c + print-icmp.c:
```
print-dccp.c(500): warning C4456: declaration of 'cp' hides previous local declaration
print-dccp.c(277): note: see declaration of 'cp'
```
(why the heck did Github merge both my changes into 1 pull request?)

Fix print-icmp.c warning

---

print-radius.c

I haven't included any unit tests, because the trivial change this is. It has been tested locally and it has been seen working there. It doesn't break any existing unit tests either.
Fun fact: this value is used to assign a VLAN to a port or WLAN user, I wouldn't be surprised if it's the most common used value for Tunnel-Type.

Add Value 13 "VLAN" to Tunnel-Type RADIUS attribute

---

print-802_11.c

This is a very old bug, and I think it's time to get fixed :-)
I'm quite sure this thing would break lots of tools based on tcpdump output, but right now there is actually no way to distinguish between dB values and positive dBm values.

dBm values get printed as dB

---

tcpdump.c

WinDump defaults to the wrong interface on my machine. Reproducing [my message](https://www.winpcap.org/pipermail/winpcap-bugs/2015-August/002178.html) to (unresponsive) [winpcap-bugs](mailto:winpcap-bugs@winpcap.org) for reference:
> WinDump -D prints the list of network interfaces, whereas WinDump -i 1 captures packets from the topmost entry in that list. So far, so good. According to https://www.winpcap.org/windump/docs/manual.htm, the same thing should happen if the executable is called without any arguments:
> > If unspecified, tcpdump searches the system interface list for the lowest numbered, configured up interface (excluding loopback). 
>
> This works on UNIX, but unfortunately behaves differently on Windows. The interface to listen on is determined with pcap_findalldevs in the …

Default to correct interface on Windows

---

tcpdump.c

The last commit only freed the remainder of the list, starting with the interface to listen on. I also changed `show_devices_and_exit()` along the lines of the last commit to make Valgrind shut up about the leak.

Free all and entire lists pcap_findalldevs() returns

---

tcpdump.c

Zerocopcy buffers in bpf was broken until recently in FreeBSD and now that
it is fixed, tcpdump is failing with insuficient capabilities when trying to
use the BIOCROTZBUF ioctl.
This commit adds BIOCROTZBUF to the list of allowed ioctls.

Fix capsicum support to work with zerocopy buffers in bpf.

---

tcpdump.c

This change is only aesthetical, it's a suggestion based on code style guidelines from the Linux Kernel.
[Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)

Avoiding conditional directives that break statements

---

tcpdump.c

Rolling over into zero filesize makes no sense. Creating a rotating
buffer of zero files makes no sense.
Modify the checks for -C and -W to accept greater than one, not greater
than zero.
Signed-off-by: Jamie Bainbridge <jamie.bainbiridge@gmail.com>

Don't accept zero -C or -W options

---

print-geneve.c

The latest versions of the Geneve draft (https://tools.ietf.org/html/draft-ietf-nvo3-geneve-02) have additional assignments for option classes. This adds support for printing them by name instead of by hex value.

Geneve TLV Option Classes

---

print-tcp.c
tcp.h

Fixes first problem in issue #516 while the second one isn't broken in tcpdump.
https://www.iana.org/assignments/tcp-parameters/tcp-parameters.xhtml
See section 3.2.3 on page 20 in http://public.ccsds.org/publications/archive/714x0b2.pdf
Review carefully because I haven't been able to test it with TCP Auth and SCPS-TP packets.

Correct TCP option Kind value for TCP Auth and add SCPS-TP.

---

tcpdump.c

If tcpdump is configured with both libcap-ng and --with-chroot, then it
needs to keep CAP_SYS_CHROOT until droproot is complete.

Don't drop CAP_SYS_CHROOT before chrooting.

---

addrtoname.c
config.h.in
configure
configure.in
tcpdump.c

The patch allows tcpdump to run sandboxed and still do name resolution.
The code is obtained from FreeBSD tree, where it was developed by
Pawel Jakub Dawidek <pjd@FreeBSD.org>
Mariusz Zaborski <oshogbo@FreeBSD.org>

Add support for libcasper library available on FreeBSD 11.0 and newer.

---

print-cfm.c

Note that the following tests fail when I run make check, it does not seem plausible that my change broke them, however in case you believe it plausible that it was my change I am including the information so you can reject it:
Failed test: pcap-invalid-version-2
1c1
\< EXIT CODE 00000100
---
\> IP6 fe80::b299:28ff:fec8:d646.6696 > ff02::1:6.6696: babel 2 (424) hello update/id request tspc hmac hmac hmac hmac hmac hmac hmac hmac
Failed test: pcap-ng-invalid-vers-2
1c1
\< EXIT CODE 00000100
---
\> IP6 fe80::20c:29ff:fe9e:c1b2 > ff02::5: OSPFv3, Hello, length 88

Fix typo in printing full name of CFM's CCM opcode value.

---

tcpdump.c

On a FreeBSD system when using tcpdump -I -i wlanN and wlanN is not a monitor mode VAP, tcpdump will print an error message saying rfmon is not supported.
Give a concise explanation as to how one might solve this problem by creating a monitor mode VAP.

On FreeBSD provide advice in case of rfmon not support error.

---

print-esp.c

This issue is described in #586.
It basically just allocates a new buffer, which is passed into the `EVP_Cipher` function. The rest is just debugging, which I'll remove.
Do you agree with this solution?

Use separate buffers for encrypted and decrypted content

---

print-ntp.c

Here are some improvements for the NTP printer to support sub-second polling intervals, MACs using 160-bit digests and reference IDs generated from IPv6 addresses. There is also a fix for printing key IDs.
I'd like to add a test for the NTP printer, but there is a problem that NTP timestamps are printed in local time and won't match the expected output unless the timezone is the same. Would it be ok to set TZ=UTC in tests/TESTonce?

Improvements of NTP printer

---

Makefile.in
addrtoname.c
config.h.in
configure
configure.in
getservent.h
missing/getservent.c

As discussed earlier in issue #640. I eventually went with a mix of C and D to remove some useless files/functions and because simply replacing a few defines/parameter didn't really work. 
I tried to keep it as universal as possible so that platforms other than windows (who don't have this) can use it as too **and** so that it won't take too much effort to make it (possibly someday) read other files as well.
It currently reads %SYSTEMROOT%\System32\drivers\etc\services ($PREFIX/etc/services if not win32) and falls back to read just [same directory as tcpdump]\services (/etc/services).
Maybe it should be the other way around, allowing user to supply their own services database, since the default one on windows is quite limited (280 entries).

Made up for missing getservent() and endservent()

---

missing/getservent.c

- fixed none _WIN32 implementation
- on windows, see if a `services `file exists in the same directory as tcpdump and use that

Updates for getservent.c

---

print-babel.c
tests/babel_auth.out

When the AE field is 0, the message applies to any routes or
neighbours.  Tcpdump used to print it as ::/0, which is confusing.

Fix printing of wildcard retractions and IHU in Babel printer.

---

tcpdump.c

In pcap for RDMA devices, on FreeBSD where we have support for capsicum
but we don't have file descriptor for a live capture we will fail with:
"tcpdump: unable to limit pcap descriptor"
We just fail to set the proper access rights - don't fail the capture.
Signed-off-by: Slava Shwartsman <slavash@mellanox.com>

Fix fail to capture on RDMA device on FreeBSD

---

tcpdump.1.in

Just what it says on the tin. \P is invalid.

Fix a broken font escape in the manual page.

---

CMakeLists.txt
cmakeconfig.h.in
config.h.in
configure
configure.ac
print-sll.c
tcpdump.c

The reason why displaying interface only for live captures is different
index when display pcap file on another machine than the one which was
doing the capture on [1].
See: GH the-tcpdump-group/libpcap#127
[1] https://lists.sandelman.ca/pipermail/tcpdump-workers/2018-July/001019.html
Signed-off-by: Petr Vorel <pvorel@suse.cz>
Suggested-by: Guy Harris <guy@alum.mit.edu>

Display interface on live captures on DLT_LINUX_SLL2

---

tcpdump.c

Previously would silently accept any of "host", "adapter", or
"adapter_unsynced" regardless of whether the interface supported
the option.

Add check for pcap warning PCAP_WARNING_TSTAMP_TYPE_NOTSUP

---

netdissect-stdinc.h

`isatty` has been deprecated in Visual Studio since [at least VS 2012](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2012/ms235388(v=vs.110)). It doesn't cause a compile error, but does generate a warning that it's not defined and is assumed to be an `extern` returning an `int`. This change includes the appropriate header, `io.h`, for [the replacement `_isatty` function](https://docs.microsoft.com/en-gb/cpp/c-runtime-library/reference/isatty?view=vs-2017) and defines `isatty` to be `_isatty` if it's not already defined.

Ensure isatty is defined on Win32.

---

print-esp.c
tcpdump.c

Added a return check for `malloc` in tcpdump.c.
Added a return check for `strsep` in print-esp.c.
Fixed a small typo.
All tests passed.

return-checks: Added a return check for malloc and for strsep

---

tcpdump.c

Current included header `sys/capability.h` is deprecated. All
supported FreeBSD versions have now the proper header `sys/capsicum.h`

Include correct capsicum header

---

CREDITS
netdissect.h
print-802_15_4.c
print.c

New link type for IEEE 802.15.4 with additional meta-data.
See https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=15429 for full specification.
No actual parsing of meta-data TLVs are performed.  The header and TLVs are skipped and the PHY payload is passed to the common IEEE 802.15.4 print function.

Support DLT_IEEE802_15_4_TAP.

---

tcpdump.1.in
tcpdump.c

Rationale: when you need to quickly start collecting packets into a savefile and you happen to need a different time stamp precision as the default, it is easy to confuse whether the proper option it is `--time-stamp-precision`, `--timestamp-precision`, or what.  These shortcuts do not change `tcpdump`'s behavior, they are equivalent to using the `--time-stamp-precision` option.
In order to present the shortcuts in `print_usage()`, it felt adequate to reshuffle the strings and group the ones related to time stamping (i.e., `--time-stamp-precision` and the included shortcuts).

Add shortcuts for setting time stamp precision

---

tests/TESTonce

solaris userland gate requires this change. will make our
life bit easier if upstream will kindly accept this change.

allow unit tests to specify an alternate tcpdump binary

---

CMakeLists.txt
Makefile.in
netdissect.h
print-arp.c
print-ipoib.c
print.c

InfiniBand support for tcpdump.
This is an in-house patch. Sent upstream for potential inclusion in future
versions of tcpdump.

InfiniBand support for tcpdump.

---

print-ether.c

The refactoring in b258556b introduced this minor error.

Fix typo that increases, instead of decreases, caplen

---

configure.ac

with_sandbox-capsicum -> with_sandbox_capsicum

fix shell variable typo and unbreak --without-sandbox-capsicum

---

print-pim.c
tests/heapoverflow-in_checksum.out
tests/pim-packet-assortment-v.out
tests/pim-packet-assortment-vv.out
tests/pim_header_asan-3.out

RFC5015 splits the one-"reserved" field in two halves, meaning that some of the fuzzed packets get printed differently with this change.

PIM Designated Forwarder Election (RFC5015)

---

tcpdump.c

This allows the "interface-less" option described in #804 .  It's possible that it should be improved (e.g., if you can't find an interface, and the dump flag is specified, it could output "Maybe you meant to add `-y EN10MB`?  Or, maybe it's common enough that it should *default* to `-y EN10MB` with a warning message?)

Do not open an interface if not needed for -d

---

print-rx.c

nd_ipv4 was created for an unaligned field access inside of packet data,
so it should not be used for the rx_cache_entry.  Use uint32_t, and use
GET_IPV4_TO_NETWORK_ORDER instead of UNALIGNED_MEMCPY() to get the data
into them.
This caused test failures when your memory layout is such that the cache data
is stored above the packet data, since the GET_IPV4_TO_NETWORK_ORDER
accessing the cache would report that the packet is truncated.

Don't use nd_ipv4 for non-packet data

---

ip6.h

ipv6.h still carries some unused, historic ECN references.
These are incompatible with the ECN signaling adopted by
IETF for both IPv4 and IPv6.
Fortunately, these references are nowhere used. Removing
these definitions should keep it this way in the future.
See also  https://reviews.freebsd.org/D23903

Remove historic ECN definitions from IPv6

---

tcpdump.c

[Request for comments]
I propose to set the default linktype to LINUX_SLL2 when capturing on the "any" device.
(if available in libpcap)
It gives useful informations: interface name, in/out with '-e' option.
libpcap support since 1.9.1 version.
The printing is currently not supported in release 4.9.3.
Already asked on the mailing list.
No one said "no".

Set default linktype LINUX_SLL2 when capturing on the "any" device

---

CMakeLists.txt
Makefile.in
netdissect.h
print-unsupported.c
print.c

This avoids to get only:
tcpdump: packet printing is not supported for link type XYZ: use -w
Set ndo->ndo_packet_number.
The default printing is like:
1  15:00:02.232595 UNSUPPORTED
0x0000:  0000 0338 0000 0000 0000 0000 0000 0000
0x0010:  1400 0000 1600 0503 0000 0000 0000 0000
0x0020:  0200 0000
2  15:00:02.232622 UNSUPPORTED
0x0000:  0000 0338 0000 0000 0000 0000 0000 0000
0x0010:  3000 0000 1400 0200 0000 0000 0000 0000
0x0020:  0208 0000 0000 0000 0800 0200 7f00 0001
[...]

[RFC] Print packets for unsupported link protocols in hexadecimal and ASCII

---

nameser.h
print-domain.c

IANA reference: https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml
I updated the comments to reference the latest RFC where they didn't already. Let me know if you'd prefer that I leave that out.
Removed the `UNSPECA` type parsing as IANA has that query type number assigned to `NID` now.

DNS: Sync types with IANA

---

print-802_11.c

In the case where the "From DS" bit is not set and the "To DS" bit is set in the Frame Control Bitmask, the comment line in the corresponding if else block was misleading that the "From DS" bit is set and the "To DS" bit is not set.

Fix the misleading comment regarding "From DS", "To DS" Frame Control Flags

---

tcpdump.1.in
tcpdump.c

In response to https://github.com/the-tcpdump-group/tcpdump/issues/884 *Add GNU-like block size suffix support to savefile's file_size*
````
[steve@localhost tcpdump]$ sudo /home/steve/out/bin/tcpdump -C 5m -w /tmp/foo
tcpdump: listening on enp0s3, link-type EN10MB (Ethernet), snapshot length 262144 bytes
^C4951 packets captured
4959 packets received by filter
0 packets dropped by kernel
[steve@localhost tcpdump]$ ls -l /tmp/foo*
-rw-r--r--. 1 root root 5244047 May  8 14:31 /tmp/foo
-rw-r--r--. 1 root root 2644025 May  8 14:31 /tmp/foo1
[steve@localhost tcpdump]$ 
````
Default behaviour remains unchanged.
````
[steve@localhost tcpdump]$ sudo rm -f /tmp/foo*
[steve@localhost tcpdump]$ sudo /home/steve/out/bin/tcpdump -C 1 -w /tmp/foo
tcpdump: listening on enp0s3, link-type EN10MB …
```

optional unit suffix on -C file size

---

print-icmp.c
print-mptcp.c

The CONTRIBUTING file advises us to "Avoid trailing tabs/spaces". This PR removes last remaining trailing whitespace from the source code, making it easier to setup a warning in case any new trailing whitespace were to be introduced.

Remove last remaining trailing whitespace

---

print-802_11.c

As per the IEEE 802.11-2016 std, section 9.3.1.9, Fig 9-32, the Block Ack control frame has the Transmitter Address field. So include this TA field when printing the BA frame to stdout if the "eflag" is enabled.

IEEE 802.11: include the "TA" field while printing Block Ack Control frame

---

configure
configure.ac

While cross-compile, `./configure --host=xxx` will output:
"checking whether printf(3) supports the z length modifier...
configure: error: in `/${path_to_tcpdump}/tcpdump':"
That is casued by AC_RUN_IFELSE, as describe in
"https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Runtime.html"
, if AC_RUN_IFELSE do not have cross-compile option, configure prints an error message and exits.
Signed-off-by: Mingrui Ren <jiladahe1997@gmail.com>

[bugfix]configure: fix error when cross-compile:

---

print-bgp.c

rfc6938
Signed-off-by: Donatas Abraitis <donatas.abraitis@gmail.com>

bgp: Deprecate DPA, ADVERTISER and RCID_PATH path attributes

---

tcpdump.c

This fixes issue #997 : Set SA_RESTART on non-lethal signals (REQ_INFO, FLUSH_PCAP) to avoid  corrupting binary pcap output

Fix #997 : Set SA_RESTART to avoid corrupting binary pcap output

---

build_common.sh

Haiku does not have an `ldd` script. This change allows us to get at least some successful cases from the build matrix by using `objdump` instead of `ldd`. Should help with #996.

build_common: fix missing ldd on Haiku

---

netdissect.h
ntp.c
print-ahcp.c
print-arista.c
print-rx.c
print-zep.c
smbutil.c
tcpdump.c
util-print.c

Have a routine that takes a buffer, a strftime format, and a struct tm * as arguments, and:
* checks whether the struct tm * is null and, if so, returns a string indicating that the date and time couldn't be converted;
* otherwise, passes it to strftime(), along with the buffer and the format argument and, if strftime() returns 0, meaning the string didn't fit into the buffer and thus that the buffer's contents are undefined, returns a string indicating that the date and time didn't fit into the buffer;
* otherwise, returns a pointer to the buffer.
Call this routine instead of directly calling strftime() in printers; that prevents printing a buffer with undefined data if the buffer isn't big enough for the string.
Also, when generating file names using an strftime format, check the return …

Have a common routine for converting dates and times to strings.

---

Makefile.in

In the GNU makefile standards, "make distclean" removes everything that's not part of the source distribution; this does *not* include the configure script or the config.h.in file, as those are in the release tarball, so that building from a source tarball doesn't require having autoconf.  This allows somebody building from the source tarball to do a "make distclean" and then reconfigure.
Do, however, remove any release tarball in make distclean, by having distclean depend on clean.

Makefile.in: don't remove configure and config.h.in in make distclean.

---

CHANGES
CMakeLists.txt
addrtoname.c
cmakeconfig.h.in
configure.ac
netdissect-stdinc.h
tcpdump.c

Let's see if this passes CI cleanly. A couple additional notes:
* There's one call to `cmake_pop_check_state()` missing from `CMakeLists.txt`, I guess it should be just before "Check for various functions in libpcap/WinPcap/Npcap.", but this discrepancy is old and seems to be irrelevant to this commit.
* The pre-existing `check_type_size("struct in6_addr" HAVE_STRUCT_IN6_ADDR)` line remains because without it my CMake fails to configure as shown below without an apparent reason. I tried to debug it, but both with and without the line the value of `CMAKE_REQUIRED_LIBRARIES` seems to be the same, so I cannot explain this failure, but it reproduces steadily.
```
-- Looking for sys/types.h
CMake Error (dev) at /usr/share/cmake-3.18/Modules/CheckIncludeFile.cmake:80 (message):
Policy CMP0075 …
```

Detect OS IPv6 support using AF_INET6 only.

---

CMakeLists.txt

We didn't completely pop the check state after we finished the checks for libpcap.

CMake: balance cmake_push_check_state() and cmake_pop_check_state().

---

print-isakmp.c

The notification type entries were crafted from the CSV files provided by IANA for the [error types] resp. [status types].
[error types]:  https://www.iana.org/assignments/ikev2-parameters/ikev2-parameters-14.csv
[status types]: https://www.iana.org/assignments/ikev2-parameters/ikev2-parameters-16.csv

IKEv2: add missing notification types

---

tcpdump.c

Hello,
one of our customer reported zombie processes when running tcpdump under load with -C/-z and I've been able to reproduce. Here's a patch suggestion, but feel free to use something else -- waitpid is also mandated by posix so there should be no portability issue (same requirement as wait) but I've only tested this on linux.
Commit message below:
Under load it's possible multiple children have been killed before we start processing the SIGCHILD signal, leaving zombie processes behind everytime we miss a process.
Reap as many processes as possible instead of assuming one handler call = one process like we currently did.
Can be reproduced by running the following commands in parallel:
- tcpdump -i lo -w /tmp/test -C 1 -z /usr/bin/true
- iperf3 -s
- iperf3 -c localhost
Test summary:
- …

child_cleanup: reap as many child processes as possible

---

.cirrus.yml

The warnings were like:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
LANGUAGE = (unset),
LC_ALL = (unset),
LANG = "en_US.UTF-8"
are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

Cirrus CI: Avoid perl warnings about setting locale, Linux task

---

tcpdump.1.in

Delete Linux 2.0 bugs from bug list.
Linux 2.0.x releases are from 1996-2004. The man page recommended upgrading to Linux 2.2, released in 1999.
https://en.wikipedia.org/wiki/Linux_kernel_version_history#Releases_up_to_2.6.0
I'm assuming these >20 year old bug references aren't that useful now.

tcpdump.1.in: Delete Linux 2.0 references

---

print-ptp.c

The IEEE 1588 (PTP) standard uses the spelling SIGNALING, with one L.
I understand that one L vs two L can vary depending on where in the world you are, but the standard uses one L so I think it's better to use that.

Fix spelling of PTP type SIGNALING

---

CHANGES
install-sh

The version of install-sh we have was made over 2 decades ago, and last edited 9 years ago.
I updated the script by running autoreconf -fiv on autoconf 2.71, and autoreconf automatically updated the script.

Update install-sh script to the latest available version

---

netdissect.h
print-ascii.c
print-bgp.c
print-isoclns.c
print-lwres.c
print-resp.c
print-smb.c
smbutil.c

1)
Update ND_BYTES_BETWEEN() macro for better accuracy
Update the macro that computes how many bytes are present, starting
at the first argument and running up to (but not including) the second
argument, and returns that as a u_int (cutting it to 32 bits on LP64
and LLP64 platforms).
This reverses, for reasons of readability, the order of the arguments
which was based on old SMB's PTR_DIFF().
With this change the number of bytes "between" given by the macro is 0
when the first argument is greater than or equal to the second argument.
This is a follow-up to f9c2c905b118b69a0b102549c1b25cca871947b5.
2)
Update ND_BYTES_AVAILABLE_AFTER() macro for better accuracy
With this change the number of bytes available in the captured data
given by the macro is 0 when the argument is greater than or …

Update ND_BYTES_BETWEEN() and ND_BYTES_AVAILABLE_AFTER() macros for better accuracy

---

netdissect.c
netdissect.h

It should rarely be called (if it's called, either the packet was cut short by snapshot-based slicing or it's malformed, or the dissector has a bug), so inlining it doesn't help much, and, as it calls longjmp(), which often expands to a call to __builtin_longjmp(), GCC won't inline it anyway (see "An Inline Function is As Fast As a Macro" in the GCC documentation), and Apple clang version 14.0.3 (clang-1403.0.22.14.1), at least, doesn't inline it, either, so you get a bunch of inlined definitions of it throughout the generated code.
Just make it a regular routine.

Make nd_trunc_longjmp() not static inline.

---

tcpdump.c

Distributions which started building --with-user to switch to an
unpriviliged user claim that the old behavior of running under root
can be restored by passing "-Z root" on the command line. However,
doing so is different from not using --with-user, as tcpdump still
drops privileges and sets supplementary user groups.
In Linux containers using user namespaces with an in-container root
user mapped to an unprivileged external user, calling setgroups() is
usually denied, as it would allow that unprivileged user to leave
groups (see user_namespaces(7) for details). Passing "-Z root" on
a --with-user build still goes through initgroups() and therefore
setgroups(), which will fail in such a container environment. This
makes tcpdump builds using --with-user effectively unusable in such …

Skip privilege dropping when using -Z root on --with-user builds

---

print-ldp.c
tests/ldp-common-session.out

This is to complete support for all the yet unsupported messages/TLVs as per the ldp-common-session.pcap testfile.
testfile output has been updated.

LDP: outstanding work to display additional TLVs and Message Types

---

parsenfsfh.c
print-nfs.c

In parsenfsfh.c, Parse_fh(), switch (fhtype), case FHT_SUNOS5, the Fsid_dev.Minor can be 257.
Thus using 257 as a flag value ("bogus") in case FHT_UNKNOWN when Opaque_Handle[] is initialized is incorrect. This value is tested in nfs_printfh() to print or not Opaque_Handle[]. This can result in a case of use-of-uninitialized-value.
To avoid this, use UINT_MAX as flag values for Fsid_dev.Minor and Fsid_dev.Major and test the two variables in nfs_printfh().
The error was:
==9391==WARNING: MemorySanitizer: use-of-uninitialized-value [...]
MemorySanitizer: use-of-uninitialized-value util-print.c:91:2 in fn_print_str
Add two XXX comments with questions.
follow-up to commit b5353b62c2c58d3ac7c8c84b2df041f5c1602b6b.

NFS: Fix a MemorySanitizer error

---

CHANGES
tcpdump.c

Symmetrical quoting looks better.
Thus s/`/'/
See '5.10 Quote Characters' in GNU Coding Standards:
https://www.gnu.org/prep/standards/standards.html#Quote-Characters
[skip ci]

Use symmetrical quotation characters in error messages

---

tcpdump.c

An explicit `tzset()` call is usually not needed as it happens implicitly the first time we call `localtime()` or `mktime()`, but in some cases (sandboxing, chroot) this may be too late.

Initialize tzcode early

---

CMakeLists.txt

Yes, we should probably fix them at some point, but not Right This Instant.
This should squelch the warnings in #1087, but leave that open, pending a decision on which release of CMake to require on non-Windows platforms.

CMake: attempt to suppress deprecation errors.

---

diag-control.h
tcpdump.c

In one place, we really *do* legitimately ignore the return value of pcap_set_datalink(). We cast its return value to void, which appears to squelch warnings from Clang, but not from at least some versions of GCC, so provide DIAG_OFF_WARN_UNUSED_RESULT/DIAG_ON_WARN_UNUSED_RESULT and use them to squelch the warning.

Have a #define to squelch -Wunused-result warnings.

---

.cirrus.yml

FreeBSD 12.4 is EOL at the end of 2023, and FreeBSD 14.0 was released recently.

Cirrus CI: drop FreeBSD 12.4 and add FreeBSD 14.0

---

CHANGES
netdissect.h
print-icmp.c
print-ip-demux.c

Remove the icmp_print() unused parameter 'bp2'.
Enable ND_LONGJMP_FROM_TCHECK and remove a 'trunc' label. Remove some redundant ND_TCHECK_*().
Reduce the scope of some variables.
Fix some indentations.
Remove some extra blank lines.

ICMP: Modernize packet parsing

---

tests/TESTrun

The typos were "\\" instead of "\\\\" (second 'fc' command).
Moreover:
Use more File::Spec->canonpath() with 'newdir' and 'diffdir' variables.

TESTrun: Fix typos in the Windows code path

---

extract.h
print-bgp.c
print-isoclns.c
print-lmp.c
print-ospf.c
print-rsvp.c

Bury the union-of-float-and-unsigned-int hack inside inline functions and define macros to call them, rather than doing the same trick in several dissectors.

Add macros to fetch big-endian 4-byte and 8-byte IEEE floating point.

---

CHANGES
build.sh
diag-control.h
tcpdump.c

To the best of my understanding, the approach is correct. If you find that `-Wstrict-prototypes` should use a macro of its own instead of piggy-backing on `DIAG_OFF_DEPRECATION`, please make your point before long.

Make illumos build warning-free.

---

CMakeLists.txt
README.md
diag-control.h
doc/README.solaris.md
print-802_15_4.c
print-bgp.c
print-dccp.c
print-juniper.c
print-lisp.c
print-mobility.c
print-pgm.c
print-pim.c
print-resp.c
print-rt6.c
smbutil.c
tcpdump.c

With these changes tcpdump passes a complete build matrix on Solaris CBE using Sun C, GCC and Clang. In theory, these changes are not supposed to break anything else.

Sun C fixups

---

tcpdump.c

Use only sizeof() and not SIZEOF_VOID_P/SIZEOF_TIME_T because these
macros could have invalid values in some macOS fat builds (See commit
170cbc8c6d484387ec7ae19ef9f4bd14dd0845e7).
This method should be future proof.
With this change we know:
whether this is a 32-bit or 64-bit build ;
whether the time_t size is 32-bit or 64-bit.

Update --version option to print 32/64-bit build and time_t size

---

util-print.c

The warnings, given by clang with -Wshorten-64-to-32, were:
```
./util-print.c:306:48: warning: implicit conversion loses integer
precision: 'const __suseconds64_t' (aka 'const long long') to 'long'
[-Wshorten-64-to-32]
ts_date_hmsfrac_print(ndo, tvp->tv_sec, tvp->tv_usec,
~~~~~~~~~~~~~~~~~~~~~                   ~~~~~^~~~~~~
./util-print.c:306:35: warning: implicit conversion loses integer
precision: 'const __time64_t' (aka 'const long long') to 'long'
[-Wshorten-64-to-32]
ts_date_hmsfrac_print(ndo, tvp->tv_sec, tvp->tv_usec,
~~~~~~~~~~~~~~~~~~~~~      ~~~~~^~~~~~
./util-print.c:315:40: warning: implicit conversion loses integer
precision: 'const __suseconds64_t' (aka 'const long long') to 'long'
[-Wshorten-64-to-32]
ts_unix_print(ndo, tvp->tv_sec, tvp->tv_usec);
~~~~~~~~~~~~~ …
```

Fix warnings when building for 32-bit and defining _TIME_BITS=64

---

print-ppp.c
print.c

This both saves the buffer for freeing later and saves the packet pointer and snapend to be restored when packet processing is complete, even if an exception is thrown with longjmp.
This means that the hex/ASCII printing in pretty_print_packet() processes the packet data as captured or read from the savefile, rather than as modified by the PPP printer, so that the bounds checking is correct.
That fixes issue #1145, which was caused by an exception being thrown by the hex/ASCII printer (which should only happen if those routines are called by a packet printer, not if they're called for the -X/-x/-A flag), which jumps back to the setjmp() that surrounds the packet printer.  Hilarity^Winfinite looping ensues.
Also, restore ndo->ndo_packetp before calling the hex/ASCII printing routine, in …

ppp: use the buffer stack for the de-escaping buffer.

---

CHANGES
CMakeLists.txt
cmakeconfig.h.in
configure.ac
tcpdump.c

Let's confirm this passes CI as expected.

Disregard setlinebuf(3), always use setvbuf(3).

---

util-print.c

On Windows in a struct timestamp, tv_sec is a long not a 64-bit time_t.
```
The problem shows:
listening on \Device\NPF_Loopback, link-type NULL (BSD loopback), snapshot length 262144 bytes
1  [localtime() or gmtime() couldn't convert the date and time].052255
IP 10.0.0.10 > 224.0.0.251: igmp v2 report 224.0.0.251
2  [localtime() or gmtime() couldn't convert the date and time].792000
IP 10.0.0.10.138 > 10.0.0.255.138: NBT UDP PACKET(138)
The warnings with clang-cl were:
util-print.c(253,18): warning: incompatible pointer types passing
'const long *' to parameter of type 'const time_t *'
(aka 'const long long *') [-Wincompatible-pointer-types]
253 |                 tm = localtime(&tv->tv_sec);
|                                ^~~~~~~~~~~
util-print.c(255,15): warning: incompatible pointer …
```

Fix incompatible pointer types with time functions calls on Windows

---

CHANGES
CMakeLists.txt
addrtoname.c
cmakeconfig.h.in
configure.ac
extract.h
netdissect.c
netdissect.h
print-sll.c
tcpdump.c

As discussed in pull request #1161.

SLL2: Translate interface indices to names on Linux only.

---

aclocal.m4

Add a first error case when trying to build a 32-bit tcpdump with a 64-bit libpcap or vice versa.
[skip ci]

Update the error message when checking for pcap_loop()

---

Makefile.in

Don't use the hacks for the rather old SunOS 4.
It's helps to do VPATH builds, e.g. 32-bit, 64-bit in two directories.
(https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html)

Makefile.in: Update the .c.o build rule

---

.appveyor.yml

(cherry picked from commit cf3566e677bd30beacbf997ca3afff1ff4831947)
[skip ci]

AppVeyor: try building with Visual Studio 2022.

---

print-esp.c

Some compilers might not understand the declaration of the ndo_error member of an netdissect_options as pointing to a function that never returns; add a /* NOTREACHED */ comment in case they recognize that as a hint.

esp: mark unreached code as such.

---

build.sh
build_common.sh
funcattrs.h

Identification examples: tcc-0.9.27, tcc-0.9.28rc
There are currently warnings such as:
print-802_11.c:3317: warning: assignment discards qualifiers from pointer target type
print-esp.c:373: warning: function might return no value: 'hexdigit'
So use: TCPDUMP_TAINTED=yes
Works on linux-amd64.
Does not work on linux-armv7l with BUILD_LIBPCAP=yes / CMAKE=yes
(Segmentation fault, libpcap dynamically linked). Works with 0.9.28rc.
TinyCC can be found at https://bellard.org/tcc/,
https://repo.or.cz/r/tinycc.git or as package on some distros.

CI: Add TinyCC (aka TCC) support

---

configure.ac

This is the one used in the Makefile depend target via INCLS.

Autoconf: Use V_INCLS to update the list of include search paths

---

configure.ac

Those might point to a directory with headers and libraries for an installed version of libpcap; if we've already decided to use a local version in the source tree next to us, don't put -I and -L flags from --with-crypto in front of them, put those flags *after* what's already in V_INCLS and LIBS.

autotools: don't put anything before -I and -L flags for local libpcap.

---

CMakeLists.txt
aclocal.m4
configure.ac

There appears to be no way to build tcpdump on macOS Ventura with Xcode 15 with the system libpcap and have the resulting program run without getting an error due to failing to find pcap_open() or pcap_findalldevs_ex() at startup.
In particular, there appears to be no way to use __builtin_available() to protect accesses to the routines that showed up in Sonoma, so that the run-time linker doesn't fail if the routine in question isn't present.  Perhaps it requires more compiler command-line arguments.
So, instead, only check for pcap_open() and pcap_findalldevs_ex() if 1) this isn't macOS or 2) we're not building with the system libpcap.

autotools, cmake: work around an Xcode 15+ issue.

---

configure.ac

First, find out where, if anywhere, ether_ntohost() is declare, *then* test whether it's buggy - using code taken from addrtoname.c to figure out what to include and, if there's nothing that works, how to work around it.
(This means that a bunch of platforms will start using ether_ntohost().)

autoconf: fix buggy ether_ntohost() test.

---

aclocal.m4

If we're not bothering to check for something with pkg-config because we don't *have* pkg-config, don't say "checking for XXX with pkg-config" and then say "oh, right, we don't *have* pkg-config".

autoconf: don't say "checking for X with pkg-config" without pkg-config.

---

aclocal.m4

Use the -s and -q flags to suppress output from grep, rather than directing the standard output and error to /dev/null; they've  been in the Single UNIX Specification since at least UNIX 98.
Wrap "Checking..." and result messages around the test.

autoconf: tweaks to the check for --static-pcap-only support.

---

print-esp.c

It's described in
https://github.com/openssl/openssl/issues/11715#issuecomment-2164442688 as being one of several routines that "are internal macros and not really suitable for the Brave New Provider World", and the bug in question complains that they're not documented.
Instead, just map "3des" to "des-ede3-cbc" ourselves.
This should fix #1175.

esp: don't use EVP_add_cipher_alias().

---

CHANGES
print-tcp.c
tests/TESTLIST
tests/geneve-gcp.out
tests/rpki-rtr-oobr-vv.out

1) Note if the Urgent Pointer is non-zero while URG flag not set.
If verbose level is > 1 (option -vv and more).
Add a test case (existing pcap printed with -vv).
2) Note if the Acknowledgment Number is non-zero while ACK flag not set.
If verbose level is > 1 (option -vv and more).
Update the outputs of 2 tests accordingly.
Like tshark/wireshark.

TCP: Print notes about Urgent Pointer and Acknowledgment Number in some cases

---

netdissect-stdinc.h

We first unconditionally define it, and then later only define it if it's already defined.  Microsoft defines it for us, but has deprecated that definition because it pollutes the ISO C namespace with a POSIXism; try just doing the conditional definition.

netdissect-stdinc: get rid of an extra definition of strdup.

---

CHANGES
print-msdp.c

Use ND_ICHECK_U() in length/type tests and add an 'invalid' label. Remove the 'trunc' label.
Move '#define ND_LONGJMP_FROM_TCHECK' just before '#include "netdissect.h"' as for all other uses.

MSDP: Modernize packet parsing

---

CHANGES
print-ntp.c
tests/ntp-v.out

NTPv4 (RFC 5905, section 7.4) and SNTPv4 (RFC 4330, section 8) formalize that if the stratum value is zero, the refid _may_ contain a printable ("designed for character displays and log files"), left justified, zero filled ASCII string for status reporting and debugging ("kiss code"). Some kiss codes are defined in the RFCs, but the list may be modified or extended in the future, and unregistered kiss codes, e.g., for experimentation and development, are possible (and are being seen in the field).
Thus, if the stratum value is zero AND the refid field begins with a printable character, assume the refid field contains a kiss code and print it.

Print NTP kiss codes for NTP debugging

---

CMakeLists.txt

CMake appears to have the notion that a build is only a cross-compile if the targt *operating system* is different.  This is an incorrect notion, as even if the target is the *same* OS but a different instruction set, you may not be able to do tests that involve compiling and running a program.
Check whether CMAKE_GENERATOR_PLATFORM is set and has a value different from that of CMAKE_HOST_SYSTEM_PROCESSOR and, if that's the case, set CMAKE_CROSSCOMPILING to TRUE.
This comes from libpcap, where the equivalent change fixed issue the-tcpdump-group/libpcap#1352.
(A different strategy may be necessary for cross-builds with UNIX toolchains.)

cmake: treat building for another ISA as a cross-compile.

---

.cirrus.yml
Makefile.in

This may avoid errors in make check, depending on the system's libpcap version.
Update the Cirrus CI configuration, linux_task, accordingly.

Makefile.in: Use a local libpcap in the releasecheck target

---

print-ip.c

Cut off the snapshot length to the end of the IP payload or the end of the data in which it's contained, whichever comes first.

ip: set the snapshot length for the payload correctly.

---

print-ip6.c

Cut off the snapshot length to the end of the IP payload or the end of the data in which it's contained, whichever comes first.

ipv6: set the snapshot length for the payload correctly.

---

extract.h
netdissect-stdinc.h
ntp.c
tcpdump.c

We require C99 support, so don't roll our own versions.

Use C99 macros to define 64-bit constants and maximum 64-bit values.

---

CMakeLists.txt

That's the simplest way to check whether we can use check_c_source_runs() to test for a suitable snprintf; it's easier than trying to find out the target instruction set architecture and comparing it with the host instruction set architecture, as CMake doesn't provide any mechanism to provide the target instruction set architecture, on all platforms, in a form that can be compared with the host instruction set architecture, and even if the target is different, we may be able to run code for that instruction set architecture if, for example, it's a 32-bit version of the instruction set architecture on which the build is being done, or if there's a binary emulator.

CMake: check whether check_c_source_runs() works.

---

CMakeLists.txt
configure.ac

Avoid trying to cast negative values to unsigned types, or doing shifts of signed types, in order not to have the test program fail if we're building with undefined-behavior sanitizers enabled.
See the-tcpdump-group/libpcap#1396 for the equivalent libpcap issue.

autotools, CMake: fix issues with snprintf test and sanitizers.

---

.appveyor.yml
cmake/Modules/FindPCAP.cmake

Add ARM64 builds for VS 2019 and VS 2022.
Fix cmake/Modules/FindPCAP.cmake to look in the right directory for pcap
libraries if the build isn't being done for 32-bit or 64-bit x86.
Use the -A flag for all generators; according to the CMake
documentation, they're supported for all generators in CMake 3.1 and
later and, on Windows, we require CMake 3.12 or later.  That ensures
that CMAKE_GENERATOR_PLATFORM will be set, so that we can use it to
determine the right directory in which to look for pcap libraries.

CI: expand the matrix for AppVeyor and fix issues that finds.

---

.cirrus.yml

We need it because we do an install of libpcap, including "make check", and "make check" requires Homebrew's coreutils in order to get the timeout command.

CI: install coreutils with Homebrew on macOS. [skip appveyor]

---

CMakeLists.txt
configure.ac

Do not check that the function is just available: first, it is in C99, so the check almost certainly is a waste of time; second, the source requires the function unconditionally; third, the subsequent "snprintf() is suitable" check implies the "snprintf() is available" part anyway.
(cherry picked from commit e1bcb7941d916285e5e502ff84dff5a15ec0b498)

Simplify the checks for snprintf().

---

.cirrus.yml

In theory, this should pass all tests.

Cirrus CI: Do not install coreutils on macOS.

---

CHANGES
tcpdump.c

If an attempt to open a capture device failed because capturing isn't supported on that device, check whether an error message with a further explanation was provided and, if so, report it.

tcpdump: show error message for PCAP_ERROR_CAPTURE_NOTSUP.

---

CMakeLists.txt

Our trick to extract a big-endian IEEE floating-point number from a packet confuses MSVC into thinking we're doing something we're not doing, or maybe just that we might do so somewhere that it can't see. Suppress the resulting warning.

Suppress bogus C4738 from MSVC.

---

configure.ac

In case some other library with which we're linking - for example, a version of libpcap that has rpcap-over-TLS support? - is causing us to link with libcrypto, don't look for libcrypto ourselves.

autotools: don't link with -lcrypto twice.

---

tcpdump.c

If we receive a TERM signal while we're shutting down, we can access a free'd pcap_t while trying to call pcap_breakloop(). We avoid this by setting the "pd" to NULL after freeing it, and don't try to use it if it's NULL.
The backtrace of the failure (in tcpdump 4.99.5) appeared as follows:
```
(gdb) where
#0  pcap_breakloop_linux (handle=0x55bc681f00f0) at ./pcap-linux.c:947
#1  0x000055bc676c40c3 in cleanup (signo=<optimized out>) at ./tcpdump.c:2929
#2  save_state_and_cleanup (sgno=<optimized out>) at ./tcpdump.c:2982
#3  <signal handler called>
#4  0x00007fb6fab7a8b8 in _fini () from /lib64/libgcc_s.so.1
#5  0x00007fb6fb65b376 in _dl_fini () at dl-fini.c:147
#6  0x00007fb6fac1f2ae in __run_exit_handlers () from /lib64/libc.so.6
#7  0x00007fb6fac1f3de in exit () from /lib64/libc.so.6 …
```

Avoid race condition when receiving signal during shutdown

---

tcpdump.c

Don't assume that a libpcap error message will include the interface name.

tcpdump: put the interface name into all open error messages.
